#Main Pipeline
name: DevSecOps Pipeline - TrackForge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: Code Quality
    uses: ./.github/workflows/code-quality.yml

  tests:
    name: Unit Tests
    needs: quality
    uses: ./.github/workflows/code-test.yml

  secrets-scan:
    name: Secret Scanning
    needs: quality
    uses: ./.github/workflows/secret-scanning.yml

  dependencies:
    name: Dependency Scan
    needs: tests
    uses: ./.github/workflows/dependency-scan.yml

  static-analysis:
    name: SAST - Semgrep
    needs: tests
    uses: ./.github/workflows/sast.yml
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  code-analysis:
    name: Code Analysis - SonarQube
    needs: tests
    uses: ./.github/workflows/sonar-qube.yml
    secrets: inherit

  image-scan:
    name: Docker Image Scan
    needs: tests
    uses: ./.github/workflows/docker-scans.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  dynamic-analysis:
    name: DAST - OWASP ZAP
    needs: tests
    uses: ./.github/workflows/dast.yml
